/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMembersDialog: typeof import('./src/components/AddMembersDialog.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Composer: typeof import('./src/components/Composer.vue')['default']
    CreateChannelDialog: typeof import('./src/components/CreateChannelDialog.vue')['default']
    CreateProjectDialog: typeof import('./src/components/CreateProjectDialog.vue')['default']
    CreateTaskDialog: typeof import('./src/components/CreateTaskDialog.vue')['default']
    EmojiPicker: typeof import('./src/components/EmojiPicker.vue')['default']
    FilesDialog: typeof import('./src/components/FilesDialog.vue')['default']
    LogTimeDialog: typeof import('./src/components/LogTimeDialog.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    NewMessageDialog: typeof import('./src/components/NewMessageDialog.vue')['default']
    PeoplePicker: typeof import('./src/components/PeoplePicker.vue')['default']
    PinnedDialog: typeof import('./src/components/PinnedDialog.vue')['default']
    PresenceDot: typeof import('./src/components/PresenceDot.vue')['default']
    ProfileDrawer: typeof import('./src/components/ProfileDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./src/components/SidebarItem.vue')['default']
    SidebarSection: typeof import('./src/components/SidebarSection.vue')['default']
    StatusMenu: typeof import('./src/components/StatusMenu.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskDialog: typeof import('./src/components/TaskDialog.vue')['default']
    ThreadPanel: typeof import('./src/components/ThreadPanel.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UpdateCard: typeof import('./src/components/UpdateCard.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
